# Detecção de Raças de Cachorros utilizando Redes Neurais

## Importações

### Importando biblioteca

In [1]:

from sys import platform
import os
import pandas as pd
from PIL import Image
import numpy as np
import random

### Importando Dataset

In [2]:
if platform == "linux" or platform == "linux2":
    folder_path = os.getcwd() + "/" + "low-resolution"
elif platform == "win32":
   folder_path = os.getcwd() + "\\" + "low-resolution"


list_images = []

for subfolder in os.listdir(folder_path):
    subfolder_path = os.path.join(folder_path, subfolder)
    
    if os.path.isdir(subfolder_path):
        for file in os.listdir(subfolder_path):
            
            file_path = os.path.join(subfolder_path, file)
            image_about = {}
            breed = subfolder.split("-")[-1]
            image_about["breed"] = breed
            image_about["filename"] = file
            image_about["path_file"] = file_path
            list_images.append(image_about)

df_images = pd.DataFrame.from_records(list_images)

### Criando modelo

In [3]:
import tensorflow as tf

2023-07-15 19:22:06.820610: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
2023-07-15 19:22:06.855143: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
2023-07-15 19:22:06.855600: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-07-15 19:22:07.767573: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT


In [4]:
model = tf.keras.models.Sequential()

In [4]:
if platform == "linux" or platform == "linux2":
    folder_path = os.getcwd() + "/" + "low-resolution"
elif platform == "win32":
   folder_path = os.getcwd() + "\\" + "low-resolution"
amostra_por_pasta = 20
dataset = []
labels = []
img_size_height = 300
img_size_width = 400

arquivos = os.listdir(folder_path)

subpastas = [subpasta for subpasta in os.listdir(folder_path)]

for subpasta in subpastas:
    subpasta_path = os.path.join(folder_path, subpasta)
    imagens = os.listdir(subpasta_path)

    # Verifica se há mais de 20 imagens na pasta
    if len(imagens) > amostra_por_pasta:
        imagens_amostradas = random.sample(imagens, amostra_por_pasta)
    else:
        imagens_amostradas = imagens

    for imagem_nome in imagens_amostradas:
        extensao = os.path.splitext(imagem_nome)[1].lower()
        
        imagem_path = os.path.join(subpasta_path, imagem_nome)
        imagem = Image.open(imagem_path)
        imagem = imagem.resize((img_size_width, img_size_height))  # Redimensiona para um tamanho comum
        imagem_array = np.array(imagem)

        dataset.append(imagem_array)
        labels.append(subpasta)

# Converte o dataset e as labels em arrays NumPy
dataset = np.array(dataset)
labels = np.array(labels)

# Exemplo de como usar o dataset e as labels
print("Tamanho do dataset:", dataset.shape)
print("Tamanho das labels:", labels.shape)
print("Exemplo de uma imagem:", dataset[0])
print("Label da imagem:", labels[0])

Tamanho do dataset: (2600, 300, 400, 3)
Tamanho das labels: (2600,)
Exemplo de uma imagem: [[[ 72  67  63]
  [ 74  69  65]
  [ 76  71  67]
  ...
  [  1   1   1]
  [  1   1   1]
  [  1   1   1]]

 [[ 74  69  65]
  [ 76  71  67]
  [ 78  73  69]
  ...
  [  1   1   1]
  [  1   1   1]
  [  1   1   1]]

 [[ 76  71  67]
  [ 78  73  69]
  [ 80  75  71]
  ...
  [  1   1   1]
  [  1   1   1]
  [  1   1   1]]

 ...

 [[199 183 183]
  [197 182 182]
  [195 182 182]
  ...
  [141 129 129]
  [140 131 130]
  [152 142 141]]

 [[196 180 180]
  [198 182 182]
  [200 188 188]
  ...
  [142 131 130]
  [141 130 129]
  [153 143 142]]

 [[193 177 177]
  [194 178 178]
  [197 185 185]
  ...
  [140 129 128]
  [139 129 128]
  [151 141 140]]]
Label da imagem: 201-n000024-schipperke
